### ISSUE TITLE
[FEATURE_REQUEST] <title>

### ISSUE THREAD

**Issue by akaagiao1** [net-breaker/sing-land#17]
### Is your feature request related to a problem? If so, please describe.

sing-box 更新到1.3.0了能不能更新咱的gui啊

### Describe the solution you'd like

sing-box 更新到1.3.0了能不能更新咱的gui啊

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by anonysoul** [comment]
new version released: https://github.com/net-breaker/sing-land/releases/tag/pre-alpha-4
